name: Auto Deploy Next.js to VPS

on:
  push:
    branches:
      - main  # Chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Lấy source code từ GitHub
        uses: actions/checkout@v3
      - name: Kiểm tra SSH kết nối
        run: |
          ssh -T root@buoncf.jp "echo 'SSH Connected Successfully!'"

