name: Deploy to VPS

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}
            cd /var/www/cicd
            git pull origin main
            npm install
            npm run dev
            # pm2 restart all  # Nếu dùng PM2 để chạy server
          EOF
